### PR TITLE
Modify inventory and location list views to add search bar functionality

### PR DESCRIPTION
**Pull request by aschmitt8**

### CODE REVIEW

**Review by danielprofili — APPROVED** [review]

**Review by jpetrillo3 — CHANGES_REQUESTED** [review]
I tried to open an inventory for one of the locations and the app crashed

**Comment by jpetrillo3** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

**Comment by danielprofili** [comment]
This only changes the view so I'm not sure how a null pointer exception could happen

**Comment by jpetrillo3** [comment]
> This only changes the view so I'm not sure how a null pointer exception could happen

Yeah you're right I'm not sure what I did to get an error because I've been playing with it and it seems fine now

**Review by jpetrillo3 — APPROVED** [review]

**Review by WahahaYes — APPROVED** [review]

**Pull request merged**
