### PR TITLE
Toolbar improvements

### PR DESCRIPTION
**Pull request by danielprofili**
Fixes the toolbar on the main screen as well as the location detail screen. Also cleans stuff up, removes unused files, etc.

### CODE REVIEW

**Comment by jpetrillo3** [comment]
There seem to be no bugs or issues with this, so I'll approve it, but there are some weird things. The toolbar is now blocking the address of the location on the location details screen; do we think the location details toolbar should say the name of the location or should we add it to the text underneath?Also the search button used to bring up a little box for text input but now it doesn't.

**Review by jpetrillo3 — APPROVED** [review]

**Comment by jpetrillo3** [comment]
Also excellent work with the tabs. They look great. And it seems like you've done a ton of work so seriously let us know if you want someone else to work on the rest of the stuff

**Comment by danielprofili** [comment]
yeah, I know that the toolbar messed up the location details screen. I figured that I should keep this pull request focused on the toolbar only and not redoing the location details screen (since that was another issue anyway). Also, I got rid of the search view because I think there's a better way to do search from the toolbar (which is why I wanted to do the toolbars in the first place).

**Review by aschmitt8 — APPROVED** [review]
this is amazing. the only (very minor) issue I could find is that when you go to the inventory view, the back arrow in the toolbar doesn't actually take you back (but you can still get back by using the phone's back button) so that can be an enhancement to work on later, but not a priority since it still works. i love how the list slides away it's so prettyyyy

**Review by AidanMulaokar — APPROVED** [review]

**Pull request merged**
