### PR TITLE
Inv to loc details

### PR DESCRIPTION
**Pull request by ewilson72**

### CODE REVIEW

**Review by aschmitt8 — CHANGES_REQUESTED** [review]
can we add something to say "inventory" so people know what they're looking at? right now, especially with one item, it's just like some floating spaghetti underneath the website

**Review by jpetrillo3 — DISMISSED** [review]
I agree with Amanda about labeling the inventory. I like the spinner for selecting your location

**Comment by jpetrillo3** [comment]
Oh I had one more comment. Why is there "FOOD" in all caps next to spaghetti lol

**Comment by ewilson72** [comment]
food is the donation category, but i didn't bother to see what the real values were

**Review by AidanMulaokar — APPROVED** [review]

**Review by AidanMulaokar — APPROVED** [review]

**Review by aschmitt8 — APPROVED** [review]

**Review by danielprofili — APPROVED** [review]

**Pull request merged**
