### PR TITLE
Search functionality

### PR DESCRIPTION
**Pull request by danielprofili**
- Searching all items (from the main page) by name
- Searching per-location items by name
- Advanced search by name, with checkboxes to choose which categories to search from

### CODE REVIEW

**Comment by aschmitt8** [comment]
seems to be working great for searching by item for a specific location, and searching by item over all locations!!

also, the toolbar was blocking the category spinner on the new item page, but by adjusting the layout i fixed it and it didn't seem to mess anything up

I'm not sure how to test the advanced search, what can I do to select a category?

**Comment by danielprofili** [comment]
Right now the advanced search is only available on the inventory screen. If you create two items with the same name (in the same location) but with different categories you can use the advanced search and see that it'll only show items from the category (or categories) that you select.

**Comment by jpetrillo3** [comment]
Okay so one small bug they may not matter for now is that if you select a category but don't type in the name of the item, it brings up nothing instead of all the items in the category

**Review by jpetrillo3 — DISMISSED** [review]

**Comment by danielprofili** [comment]
> Okay so one small bug they may not matter for now is that if you select a category but don't type in the name of the item, it brings up nothing instead of all the items in the category

That's pretty easy to fix, I'll do it in a hot sec

**Comment by danielprofili** [comment]
Fixed @jpetrillo3 's bug

**Review by AidanMulaokar — APPROVED** [review]

**Review by aschmitt8 — APPROVED** [review]

**Review by jpetrillo3 — APPROVED** [review]

**Pull request merged**
